[2024-02-13T06:58:20.945+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deverlop_model.prepare_data_set manual__2024-02-13T06:56:49.084028+00:00 [queued]>
[2024-02-13T06:58:20.953+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deverlop_model.prepare_data_set manual__2024-02-13T06:56:49.084028+00:00 [queued]>
[2024-02-13T06:58:20.954+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T06:58:21.007+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): prepare_data_set> on 2024-02-13 06:56:49.084028+00:00
[2024-02-13T06:58:21.020+0000] {standard_task_runner.py:60} INFO - Started process 186 to run task
[2024-02-13T06:58:21.023+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deverlop_model', 'prepare_data_set', 'manual__2024-02-13T06:56:49.084028+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp44rh7wxm']
[2024-02-13T06:58:21.026+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask prepare_data_set
[2024-02-13T06:58:21.195+0000] {task_command.py:423} INFO - Running <TaskInstance: deverlop_model.prepare_data_set manual__2024-02-13T06:56:49.084028+00:00 [running]> on host 3346c6dff994
[2024-02-13T06:58:21.442+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rtn' AIRFLOW_CTX_DAG_ID='deverlop_model' AIRFLOW_CTX_TASK_ID='prepare_data_set' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T06:56:49.084028+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-13T06:56:49.084028+00:00'
[2024-02-13T06:58:21.465+0000] {docker.py:359} INFO - Starting docker container from image python:3.8
[2024-02-13T06:58:26.472+0000] {docker.py:429} INFO - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2024-02-13T06:58:27.012+0000] {docker.py:429} INFO - [notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[2024-02-13T06:58:32.178+0000] {docker.py:429} INFO - READ DATA :  DataSets : 2024-02-13 06:58:13.281161  timestamp :  2024-02-13 06:58:32.173443
[2024-02-13T06:58:34.679+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deverlop_model, task_id=prepare_data_set, execution_date=20240213T065649, start_date=20240213T065820, end_date=20240213T065834
[2024-02-13T06:58:34.750+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-13T06:58:34.764+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
