[2024-02-14T02:56:15.201+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deverlop_model.StartJob manual__2024-02-14T02:56:13.851291+00:00 [queued]>
[2024-02-14T02:56:15.208+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deverlop_model.StartJob manual__2024-02-14T02:56:13.851291+00:00 [queued]>
[2024-02-14T02:56:15.208+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-14T02:56:15.222+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): StartJob> on 2024-02-14 02:56:13.851291+00:00
[2024-02-14T02:56:15.230+0000] {standard_task_runner.py:60} INFO - Started process 1576 to run task
[2024-02-14T02:56:15.233+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deverlop_model', 'StartJob', 'manual__2024-02-14T02:56:13.851291+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp0p6pnmvj']
[2024-02-14T02:56:15.235+0000] {standard_task_runner.py:88} INFO - Job 157: Subtask StartJob
[2024-02-14T02:56:15.289+0000] {task_command.py:423} INFO - Running <TaskInstance: deverlop_model.StartJob manual__2024-02-14T02:56:13.851291+00:00 [running]> on host 6e2ff7d2ffd0
[2024-02-14T02:56:15.367+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rtn' AIRFLOW_CTX_DAG_ID='deverlop_model' AIRFLOW_CTX_TASK_ID='StartJob' AIRFLOW_CTX_EXECUTION_DATE='2024-02-14T02:56:13.851291+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-14T02:56:13.851291+00:00'
[2024-02-14T02:56:15.369+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-14T02:56:15.370+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo StartJob && mkdir /***_base/dags/data/20240214']
[2024-02-14T02:56:15.381+0000] {subprocess.py:86} INFO - Output:
[2024-02-14T02:56:15.383+0000] {subprocess.py:93} INFO - StartJob
[2024-02-14T02:56:15.384+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/***_base/dags/data/20240214’: No such file or directory
[2024-02-14T02:56:15.385+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-14T02:56:15.394+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-14T02:56:15.397+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=deverlop_model, task_id=StartJob, execution_date=20240214T025613, start_date=20240214T025615, end_date=20240214T025615
[2024-02-14T02:56:15.408+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 157 for task StartJob (Bash command failed. The command returned a non-zero exit code 1.; 1576)
[2024-02-14T02:56:15.447+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-14T02:56:15.466+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
