[2024-02-13T08:40:20.198+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T08:39:56.939584+00:00 [queued]>
[2024-02-13T08:40:20.206+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T08:39:56.939584+00:00 [queued]>
[2024-02-13T08:40:20.207+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T08:40:20.220+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): data_sets> on 2024-02-13 08:39:56.939584+00:00
[2024-02-13T08:40:20.226+0000] {standard_task_runner.py:60} INFO - Started process 516 to run task
[2024-02-13T08:40:20.230+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deverlop_model', 'data_sets', 'scheduled__2024-02-13T08:39:56.939584+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp5n74v65n']
[2024-02-13T08:40:20.233+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask data_sets
[2024-02-13T08:40:20.277+0000] {task_command.py:423} INFO - Running <TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T08:39:56.939584+00:00 [running]> on host cd7e09605de3
[2024-02-13T08:40:20.346+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rtn' AIRFLOW_CTX_DAG_ID='deverlop_model' AIRFLOW_CTX_TASK_ID='data_sets' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T08:39:56.939584+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-13T08:39:56.939584+00:00'
[2024-02-13T08:40:20.362+0000] {docker.py:359} INFO - Starting docker container from image python:3.8
[2024-02-13T08:40:22.055+0000] {docker.py:429} INFO - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2024-02-13T08:40:27.247+0000] {docker.py:429} INFO - [notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[2024-02-13T08:40:32.368+0000] {docker.py:429} INFO - READ DATA :  HELLO WORLD  timestamp :  2024-02-13 08:40:32.364565
[2024-02-13T08:40:32.815+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deverlop_model, task_id=data_sets, execution_date=20240213T083956, start_date=20240213T084020, end_date=20240213T084032
[2024-02-13T08:40:32.842+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-13T08:40:32.862+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
