[2024-02-14T03:00:01.702+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deverlop_model.StartJob scheduled__2024-02-14T02:55:00+00:00 [queued]>
[2024-02-14T03:00:01.710+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deverlop_model.StartJob scheduled__2024-02-14T02:55:00+00:00 [queued]>
[2024-02-14T03:00:01.711+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-14T03:00:01.725+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): StartJob> on 2024-02-14 02:55:00+00:00
[2024-02-14T03:00:01.732+0000] {standard_task_runner.py:60} INFO - Started process 1658 to run task
[2024-02-14T03:00:01.735+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deverlop_model', 'StartJob', 'scheduled__2024-02-14T02:55:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpbkg3lz18']
[2024-02-14T03:00:01.738+0000] {standard_task_runner.py:88} INFO - Job 164: Subtask StartJob
[2024-02-14T03:00:01.782+0000] {task_command.py:423} INFO - Running <TaskInstance: deverlop_model.StartJob scheduled__2024-02-14T02:55:00+00:00 [running]> on host 6e2ff7d2ffd0
[2024-02-14T03:00:01.842+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rtn' AIRFLOW_CTX_DAG_ID='deverlop_model' AIRFLOW_CTX_TASK_ID='StartJob' AIRFLOW_CTX_EXECUTION_DATE='2024-02-14T02:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-14T02:55:00+00:00'
[2024-02-14T03:00:01.844+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-14T03:00:01.846+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo StartJob && mkdir /opt/***/dags/data/2024-02-14']
[2024-02-14T03:00:01.856+0000] {subprocess.py:86} INFO - Output:
[2024-02-14T03:00:01.858+0000] {subprocess.py:93} INFO - StartJob
[2024-02-14T03:00:01.859+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/***/dags/data/2024-02-14’: File exists
[2024-02-14T03:00:01.860+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-14T03:00:01.868+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-14T03:00:01.870+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=deverlop_model, task_id=StartJob, execution_date=20240214T025500, start_date=20240214T030001, end_date=20240214T030001
[2024-02-14T03:00:01.879+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 164 for task StartJob (Bash command failed. The command returned a non-zero exit code 1.; 1658)
[2024-02-14T03:00:01.908+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-14T03:00:01.926+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
