[2024-02-13T07:46:56.656+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deverlop_model.prepare_data_set manual__2024-02-13T07:46:45.261735+00:00 [queued]>
[2024-02-13T07:46:56.665+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deverlop_model.prepare_data_set manual__2024-02-13T07:46:45.261735+00:00 [queued]>
[2024-02-13T07:46:56.666+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T07:46:56.680+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): prepare_data_set> on 2024-02-13 07:46:45.261735+00:00
[2024-02-13T07:46:56.687+0000] {standard_task_runner.py:60} INFO - Started process 1018 to run task
[2024-02-13T07:46:56.690+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deverlop_model', 'prepare_data_set', 'manual__2024-02-13T07:46:45.261735+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp7gx_k_75']
[2024-02-13T07:46:56.693+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask prepare_data_set
[2024-02-13T07:46:56.741+0000] {task_command.py:423} INFO - Running <TaskInstance: deverlop_model.prepare_data_set manual__2024-02-13T07:46:45.261735+00:00 [running]> on host 3346c6dff994
[2024-02-13T07:46:56.814+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rtn' AIRFLOW_CTX_DAG_ID='deverlop_model' AIRFLOW_CTX_TASK_ID='prepare_data_set' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T07:46:45.261735+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-13T07:46:45.261735+00:00'
[2024-02-13T07:46:56.832+0000] {docker.py:359} INFO - Starting docker container from image python:3.8
[2024-02-13T07:46:58.710+0000] {docker.py:429} INFO - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2024-02-13T07:46:58.960+0000] {docker.py:429} INFO - [notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[2024-02-13T07:47:04.070+0000] {docker.py:429} INFO - READ DATA :  DataSets : 2024-02-13 07:46:54.613439  timestamp :  2024-02-13 07:47:04.067403
[2024-02-13T07:47:04.511+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deverlop_model, task_id=prepare_data_set, execution_date=20240213T074645, start_date=20240213T074656, end_date=20240213T074704
[2024-02-13T07:47:04.569+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-13T07:47:04.584+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
