[2024-02-13T07:15:37.555+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T07:15:06.257035+00:00 [queued]>
[2024-02-13T07:15:37.562+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T07:15:06.257035+00:00 [queued]>
[2024-02-13T07:15:37.562+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T07:15:37.574+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): data_sets> on 2024-02-13 07:15:06.257035+00:00
[2024-02-13T07:15:37.580+0000] {standard_task_runner.py:60} INFO - Started process 528 to run task
[2024-02-13T07:15:37.583+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deverlop_model', 'data_sets', 'scheduled__2024-02-13T07:15:06.257035+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmp4xw27tcq']
[2024-02-13T07:15:37.585+0000] {standard_task_runner.py:88} INFO - Job 39: Subtask data_sets
[2024-02-13T07:15:37.622+0000] {task_command.py:423} INFO - Running <TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T07:15:06.257035+00:00 [running]> on host 3346c6dff994
[2024-02-13T07:15:37.685+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rtn' AIRFLOW_CTX_DAG_ID='deverlop_model' AIRFLOW_CTX_TASK_ID='data_sets' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T07:15:06.257035+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-13T07:15:06.257035+00:00'
[2024-02-13T07:15:37.700+0000] {docker.py:359} INFO - Starting docker container from image python:3.8
[2024-02-13T07:15:39.328+0000] {docker.py:429} INFO - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2024-02-13T07:15:39.634+0000] {docker.py:429} INFO - [notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[2024-02-13T07:15:44.765+0000] {docker.py:429} INFO - READ DATA :  HELLO WORLD  timestamp :  2024-02-13 07:15:44.760350
[2024-02-13T07:15:45.223+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deverlop_model, task_id=data_sets, execution_date=20240213T071506, start_date=20240213T071537, end_date=20240213T071545
[2024-02-13T07:15:45.261+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-13T07:15:45.276+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
