[2024-02-13T08:04:09.417+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deverlop_model.prepare_data_set manual__2024-02-13T08:03:59.087993+00:00 [queued]>
[2024-02-13T08:04:09.425+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deverlop_model.prepare_data_set manual__2024-02-13T08:03:59.087993+00:00 [queued]>
[2024-02-13T08:04:09.426+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T08:04:09.440+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): prepare_data_set> on 2024-02-13 08:03:59.087993+00:00
[2024-02-13T08:04:09.447+0000] {standard_task_runner.py:60} INFO - Started process 1318 to run task
[2024-02-13T08:04:09.451+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deverlop_model', 'prepare_data_set', 'manual__2024-02-13T08:03:59.087993+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpd_51vbwc']
[2024-02-13T08:04:09.453+0000] {standard_task_runner.py:88} INFO - Job 57: Subtask prepare_data_set
[2024-02-13T08:04:09.496+0000] {task_command.py:423} INFO - Running <TaskInstance: deverlop_model.prepare_data_set manual__2024-02-13T08:03:59.087993+00:00 [running]> on host 3346c6dff994
[2024-02-13T08:04:09.570+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rtn' AIRFLOW_CTX_DAG_ID='deverlop_model' AIRFLOW_CTX_TASK_ID='prepare_data_set' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T08:03:59.087993+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-13T08:03:59.087993+00:00'
[2024-02-13T08:04:09.587+0000] {docker.py:359} INFO - Starting docker container from image python:3.8
[2024-02-13T08:04:11.285+0000] {docker.py:429} INFO - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2024-02-13T08:04:11.527+0000] {docker.py:429} INFO - [notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[2024-02-13T08:04:16.610+0000] {docker.py:429} INFO - READ DATA :  DataSets : 2024-02-13 08:04:07.902519  timestamp :  2024-02-13 08:04:16.608077
[2024-02-13T08:04:17.006+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deverlop_model, task_id=prepare_data_set, execution_date=20240213T080359, start_date=20240213T080409, end_date=20240213T080417
[2024-02-13T08:04:17.039+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-13T08:04:17.050+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
