[2024-02-13T07:07:41.366+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T07:07:28.415738+00:00 [queued]>
[2024-02-13T07:07:41.376+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T07:07:28.415738+00:00 [queued]>
[2024-02-13T07:07:41.377+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T07:07:41.395+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): data_sets> on 2024-02-13 07:07:28.415738+00:00
[2024-02-13T07:07:41.402+0000] {standard_task_runner.py:60} INFO - Started process 355 to run task
[2024-02-13T07:07:41.406+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'deverlop_model', 'data_sets', 'scheduled__2024-02-13T07:07:28.415738+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpt0408373']
[2024-02-13T07:07:41.408+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask data_sets
[2024-02-13T07:07:41.454+0000] {task_command.py:423} INFO - Running <TaskInstance: deverlop_model.data_sets scheduled__2024-02-13T07:07:28.415738+00:00 [running]> on host 3346c6dff994
[2024-02-13T07:07:41.548+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rtn' AIRFLOW_CTX_DAG_ID='deverlop_model' AIRFLOW_CTX_TASK_ID='data_sets' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T07:07:28.415738+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-13T07:07:28.415738+00:00'
[2024-02-13T07:07:41.570+0000] {docker.py:359} INFO - Starting docker container from image python:3.8
[2024-02-13T07:07:43.498+0000] {docker.py:429} INFO - WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2024-02-13T07:07:43.756+0000] {docker.py:429} INFO - [notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[2024-02-13T07:07:48.937+0000] {docker.py:429} INFO - READ DATA :  HELLO WORLD  timestamp :  2024-02-13 07:07:48.933983
[2024-02-13T07:07:49.444+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=deverlop_model, task_id=data_sets, execution_date=20240213T070728, start_date=20240213T070741, end_date=20240213T070749
[2024-02-13T07:07:49.490+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-13T07:07:49.513+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
